# Generated by Django 3.2.12 on 2023-04-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Person_name',
        ),
    ]
